// <auto-generated />
using System;
using MVCPROJE2_BLOGPROJE.DATAACCESS.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVCPROJE2_BLOGPROJE.DATAACCESS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210715192123_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVCPROJE2_BLOGPROJE.CORE.Entities.Konu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KonuBasliklari")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("ID");

                    b.ToTable("Konular");
                });

            modelBuilder.Entity("MVCPROJE2_BLOGPROJE.CORE.Entities.KonuMakale", b =>
                {
                    b.Property<int>("KonuID")
                        .HasColumnType("int");

                    b.Property<int>("MakaleID")
                        .HasColumnType("int");

                    b.HasKey("KonuID", "MakaleID");

                    b.HasIndex("MakaleID");

                    b.ToTable("KonuMakale");
                });

            modelBuilder.Entity("MVCPROJE2_BLOGPROJE.CORE.Entities.Makale", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KonuID")
                        .HasColumnType("int");

                    b.Property<string>("MakaleBasligi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MakaleIcerigi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MakaleResim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OkunmaSayisi")
                        .HasColumnType("int");

                    b.Property<int>("UyeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UyeID");

                    b.ToTable("Makaleler");
                });

            modelBuilder.Entity("MVCPROJE2_BLOGPROJE.CORE.Entities.Uye", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KullaniciAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("KullaniciResim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailAdresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Uyeler");
                });

            modelBuilder.Entity("MVCPROJE2_BLOGPROJE.CORE.Entities.UyeKonu", b =>
                {
                    b.Property<int>("UyeID")
                        .HasColumnType("int");

                    b.Property<int>("KonuID")
                        .HasColumnType("int");

                    b.HasKey("UyeID", "KonuID");

                    b.HasIndex("KonuID");

                    b.ToTable("UyeKonu");
                });

            modelBuilder.Entity("MVCPROJE2_BLOGPROJE.CORE.Entities.KonuMakale", b =>
                {
                    b.HasOne("MVCPROJE2_BLOGPROJE.CORE.Entities.Konu", "Konu")
                        .WithMany("KonularMakaleler")
                        .HasForeignKey("KonuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVCPROJE2_BLOGPROJE.CORE.Entities.Makale", "Makale")
                        .WithMany("KonularMakaleler")
                        .HasForeignKey("MakaleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Konu");

                    b.Navigation("Makale");
                });

            modelBuilder.Entity("MVCPROJE2_BLOGPROJE.CORE.Entities.Makale", b =>
                {
                    b.HasOne("MVCPROJE2_BLOGPROJE.CORE.Entities.Uye", "Uye")
                        .WithMany("Makaleler")
                        .HasForeignKey("UyeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("MVCPROJE2_BLOGPROJE.CORE.Entities.UyeKonu", b =>
                {
                    b.HasOne("MVCPROJE2_BLOGPROJE.CORE.Entities.Konu", "Konu")
                        .WithMany("UyelerKonular")
                        .HasForeignKey("KonuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVCPROJE2_BLOGPROJE.CORE.Entities.Uye", "Uye")
                        .WithMany("UyelerKonular")
                        .HasForeignKey("UyeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Konu");

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("MVCPROJE2_BLOGPROJE.CORE.Entities.Konu", b =>
                {
                    b.Navigation("KonularMakaleler");

                    b.Navigation("UyelerKonular");
                });

            modelBuilder.Entity("MVCPROJE2_BLOGPROJE.CORE.Entities.Makale", b =>
                {
                    b.Navigation("KonularMakaleler");
                });

            modelBuilder.Entity("MVCPROJE2_BLOGPROJE.CORE.Entities.Uye", b =>
                {
                    b.Navigation("Makaleler");

                    b.Navigation("UyelerKonular");
                });
#pragma warning restore 612, 618
        }
    }
}
